name: Sync Public to Private

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # This will trigger the workflow only when changes occur within the 'docs' directory or its subdirectories

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Sync Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PRIVATE_REPO }}
          repository: AnandarajRaman/private
          event-type: sync-changes
          client-payload: '{"source_repo": "AnandarajRaman/public"}
          
