name: Sync Public to Private

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config user.email "anandaraj.raman@syncfusion.com"
          git config user.name "AnandarajRaman"
      
      - name: Push changes to private repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PRIVATE_REPO }}
          branch: main
          repository: AnandarajRaman/private
